# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: receipts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.item_pb2 as item__pb2
import proto.store_pb2 as store__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='receipts.proto',
  package='proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0ereceipts.proto\x12\x05proto\x1a\nitem.proto\x1a\x0bstore.proto\"z\n\x08Receipts\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x14\n\x0c\x63reated_time\x18\x02 \x01(\x03\x12\x13\n\x0btotal_price\x18\x03 \x01(\x03\x12\x1b\n\x05store\x18\n \x01(\x0b\x32\x0c.proto.Store\x12\x1a\n\x05items\x18\x14 \x03(\x0b\x32\x0b.proto.Itemb\x06proto3')
  ,
  dependencies=[item__pb2.DESCRIPTOR,store__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RECEIPTS = _descriptor.Descriptor(
  name='Receipts',
  full_name='proto.Receipts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.Receipts.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='created_time', full_name='proto.Receipts.created_time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_price', full_name='proto.Receipts.total_price', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='store', full_name='proto.Receipts.store', index=3,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='proto.Receipts.items', index=4,
      number=20, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=172,
)

_RECEIPTS.fields_by_name['store'].message_type = store__pb2._STORE
_RECEIPTS.fields_by_name['items'].message_type = item__pb2._ITEM
DESCRIPTOR.message_types_by_name['Receipts'] = _RECEIPTS

Receipts = _reflection.GeneratedProtocolMessageType('Receipts', (_message.Message,), dict(
  DESCRIPTOR = _RECEIPTS,
  __module__ = 'receipts_pb2'
  # @@protoc_insertion_point(class_scope:proto.Receipts)
  ))
_sym_db.RegisterMessage(Receipts)


# @@protoc_insertion_point(module_scope)
